/**~~Comment~~**
  Loaded at launch
**~~~~**/
export const RESIZE = 'RESIZE';
export const REQUEST_PROJECT_FILES = 'REQUEST_PROJECT_FILES';
export const POLL_PREMIERE_CHILDREN_START = 'POLL_PREMIERE_CHILDREN_START';
export const REQUEST_PREMIERE_CHILDREN = 'REQUEST_PREMIERE_CHILDREN';
export const REQUEST_PREMIERE_CHILDREN_SUCCESS = 'REQUEST_PREMIERE_CHILDREN_SUCCESS';

//UI
export const HIDE_LOADER_PROGRESS = 'HIDE_LOADER_PROGRESS';

//XMP METAData
export const REQUEST_PREMIERE_FILES_METADATA = 'REQUEST_PREMIERE_FILES_METADATA';
export const REQUEST_PREMIERE_FILES_METADATA_PROGRESS = 'REQUEST_PREMIERE_FILES_METADATA_PROGRESS';
export const REQUEST_PREMIERE_FILES_METADATA_SUCCESS = 'REQUEST_PREMIERE_FILES_METADATA_SUCCESS';
export const REQUEST_PREMIERE_FILE_METADATA_SUCCESS = 'REQUEST_PREMIERE_FILE_METADATA_SUCCESS';
export const REQUEST_PREMIERE_FILE_METADATA_FAILURE = 'REQUEST_PREMIERE_FILE_METADATA_FAILURE';

export const OPEN_FILE_SOURCE_MONITOR = 'OPEN_FILE_SOURCE_MONITOR';
export const OPEN_FILE_SOURCE_MONITOR_SUCCESS = 'OPEN_FILE_SOURCE_MONITOR_SUCCESS';

export const QUERY_CHANGED = 'QUERY_CHANGED';


/***************

***************/
export const APP_INSTRUCTIONS_SET = 'APP_INSTRUCTIONS_SET';